file1=open("output.txt",'a')
a=input("Enter Text to write to the file: ")
try:
    file1.write(a)
    print("Data Successfully Written to output.txt")
    b=input("Enter Additional text to append: ")
    file1.write("\n"+b)
    print("Data Successfully Appended to output.txt")
except Exception:
    print("Some error occured")
file1.close()
file2=open("output.txt",'r')
i=file2.read()
print("Final Content of output.txt: ")
print(i)
file2.close()
